import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Copy, ShieldCheck, X } from "lucide-react";

export default function DepositModal({ onClose, onNotify }: { onClose: () => void; onNotify: (message: string) => void }) {
  const [asset, setAsset] = useState("USDC");
  const [network, setNetwork] = useState("Ethereum");
  const [amount, setAmount] = useState("");
  const [txHash, setTxHash] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const destination = trpc.deposits.destination.useQuery({ asset, network });
  const createIntent = trpc.deposits.createIntent.useMutation({ onSuccess: () => { setSubmitted(true); onNotify("Deposit submitted as pending review."); } });
  return <div className="deposit-overlay" onClick={onClose}><div className="deposit-modal" onClick={event => event.stopPropagation()}><div className="modal-heading"><div><p className="app-kicker">FUND ACCOUNT / PENDING REVIEW</p><h2>{submitted ? "Deposit pending" : "Make a deposit"}</h2></div><button className="icon-button" onClick={onClose}><X size={18} /></button></div>{submitted ? <div className="deposit-state"><CheckCircle2 size={30} /><h3>Transaction history updated</h3><p>Your {asset} deposit is now <b>under review</b>. It will remain pending until an operator confirms the transaction.</p><button className="modal-primary" onClick={onClose}>RETURN TO WALLET</button></div> : <><label className="field-label">ASSET<select value={asset} onChange={event => setAsset(event.target.value)}><option>USDC</option><option>USDT</option><option>ETH</option><option>BTC</option></select></label><label className="field-label">NETWORK<select value={network} onChange={event => setNetwork(event.target.value)}><option>Ethereum</option><option>Bitcoin</option><option>Polygon</option><option>Solana</option></select></label>{destination.data ? <><p className="address-label">ADMIN-CONFIGURED RECEIVING ADDRESS</p><div className="address-box"><span>{destination.data.address}</span><button onClick={() => { navigator.clipboard?.writeText(destination.data!.address); onNotify("Receiving address copied."); }}><Copy size={16} /></button></div>{destination.data.memo && <p className="compliance-copy">Memo / tag: <b>{destination.data.memo}</b></p>}<label className="field-label">AMOUNT (OPTIONAL)<input value={amount} onChange={event => setAmount(event.target.value)} inputMode="decimal" placeholder="0.00" /></label><label className="field-label">TRANSACTION HASH (OPTIONAL)<input value={txHash} onChange={event => setTxHash(event.target.value)} placeholder="Paste hash after sending" /></label><p className="deposit-warning"><ShieldCheck size={14} />Funds are not credited automatically. Your submission is recorded as pending until manually reviewed.</p><button className="modal-primary" disabled={createIntent.isPending} onClick={() => createIntent.mutate({ asset, network, amount: amount || undefined, txHash: txHash || undefined })}>{createIntent.isPending ? "SUBMITTING…" : "SUBMIT PENDING DEPOSIT"}</button></> : <div className="deposit-state"><p>No receiving address is configured for {asset} on {network}. Ask an administrator to configure it before depositing.</p><button className="modal-primary" onClick={onClose}>CLOSE</button></div>}</>}</div></div>;
}
